// DO NOT EDIT. Generated by scripts/i18n/generate.py from locales.json.
package com.elabify.app.maknoon.ui.theme

/**
 * The roster of shipped locales. Mirror of the iOS AppLanguageCatalog; per the
 * project rule iOS is the reference and Android follows.
 *
 * `check.py` G1 asserts this agrees with locales.json, res/values-*,
 * locales_config.xml and the iOS side.
 */
object AppLanguageCatalog {

    data class Entry(
        val code: String,
        /** For sorting and search; stable regardless of the current UI language. */
        val englishName: String,
        /**
         * Shown as the primary label. NEVER translated: someone looking for
         * 简体中文 cannot find "Chinese (Simplified)" in a language they do not
         * yet read.
         */
        val selfName: String,
        val isRTL: Boolean,
        /** Resource qualifier. `b+` form where the tag is not bare ISO 639-1. */
        val androidQualifier: String,
    )

    /** Ordered by English name so picker order is stable across UI languages. */
    val all: List<Entry> = listOf(
        Entry("en", "English", "English", false, "values"),
        Entry("ar", "Arabic", "العربية", true, "values-ar"),
        Entry("zh-Hans", "Chinese (Simplified)", "简体中文", false, "values-b+zh+Hans"),
        Entry("zh-Hant", "Chinese (Traditional)", "繁體中文", false, "values-b+zh+Hant"),
        Entry("es", "Spanish", "Español", false, "values-es"),
        Entry("hi", "Hindi", "हिन्दी", false, "values-hi"),
        Entry("fil", "Filipino", "Filipino", false, "values-b+fil"),
        Entry("pt", "Portuguese", "Português", false, "values-pt"),
        Entry("ja", "Japanese", "日本語", false, "values-ja"),
        Entry("ru", "Russian", "Русский", false, "values-ru"),
        Entry("ur", "Urdu", "اردو", true, "values-ur"),
        Entry("fr", "French", "Français", false, "values-fr"),
        Entry("de", "German", "Deutsch", false, "values-de"),
        Entry("ku", "Kurdish (Kurmanji)", "Kurmancî", false, "values-ku"),
        Entry("ckb", "Kurdish (Sorani)", "کوردیی ناوەندی", true, "values-b+ckb"),
        Entry("bn", "Bengali", "বাংলা", false, "values-bn"),
        Entry("ml", "Malayalam", "മലയാളം", false, "values-ml"),
        Entry("ta", "Tamil", "தமிழ்", false, "values-ta"),
        Entry("he", "Hebrew", "עברית", true, "values-b+he"),
        Entry("fa", "Persian", "فارسی", true, "values-fa"),
        Entry("ko", "Korean", "한국어", false, "values-ko"),
        Entry("it", "Italian", "Italiano", false, "values-it"),
        Entry("nl", "Dutch", "Nederlands", false, "values-nl"),
        Entry("tr", "Turkish", "Türkçe", false, "values-tr"),
        Entry("sw", "Swahili", "Kiswahili", false, "values-sw"),
        Entry("aa", "Afar", "Qafar af", false, "values-aa"),
        Entry("am", "Amharic", "አማርኛ", false, "values-am"),
        Entry("om", "Oromo", "Oromoo", false, "values-om"),
        Entry("so", "Somali", "Soomaali", false, "values-so"),
        Entry("ti", "Tigrinya", "ትግርኛ", false, "values-ti"),
        Entry("vi", "Vietnamese", "Tiếng Việt", false, "values-vi"),
    )

    /** Single source of the RTL set: ar, ur, he, fa, ckb. `ku` is Latin, so LTR. */
    val rtlCodes: Set<String> = setOf("ar", "ur", "ckb", "he", "fa")

    fun entry(code: String): Entry? = all.firstOrNull { it.code == code }
}
